// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vatmuwktcouvpstqhbih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhdG11d2t0Y291dnBzdHFoYmloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDkzMzEsImV4cCI6MjA3MTIyNTMzMX0.VT86RuWv6CrDAN80LHdY_nxGfb5aIqQfPUZFN9LYdJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});